In [2]:
!pip install tweepy

Collecting tweepy
  Downloading https://files.pythonhosted.org/packages/d5/5f/daac4b4e9b30d7d2a6fdd16a880ff79f27918fe388e4dfc1983dec3a9876/tweepy-3.7.0-py2.py3-none-any.whl
Requirement already satisfied: requests>=2.11.1 in ./anaconda3/lib/python3.6/site-packages (from tweepy) (2.21.0)
Requirement already satisfied: PySocks>=1.5.7 in ./anaconda3/lib/python3.6/site-packages (from tweepy) (1.6.8)
Requirement already satisfied: six>=1.10.0 in ./anaconda3/lib/python3.6/site-packages (from tweepy) (1.12.0)
Collecting requests-oauthlib>=0.7.0 (from tweepy)
  Downloading https://files.pythonhosted.org/packages/c2/e2/9fd03d55ffb70fe51f587f20bcf407a6927eb121de86928b34d162f0b1ac/requests_oauthlib-1.2.0-py2.py3-none-any.whl
Requirement already satisfied: idna<2.9,>=2.5 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.11.1->tweepy) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.11.1->tweepy) (2018.11.29)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.11.1->tweepy) (1.24.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./anaconda3/lib/python3.6/site-packages (from requests>=2.11.1->tweepy) (3.0.4)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->tweepy)
  Downloading https://files.pythonhosted.org/packages/16/95/699466b05b72b94a41f662dc9edf87fda4289e3602ecd42d27fcaddf7b56/oauthlib-3.0.1-py2.py3-none-any.whl (142kB)
    100% |████████████████████████████████| 143kB 116kB/s ta 0:00:01
Installing collected packages: oauthlib, requests-oauthlib, tweepy
Successfully installed oauthlib-3.0.1 requests-oauthlib-1.2.0 tweepy-3.7.0

In [1]:
import tweepy

In [5]:
if __name__ == '__main__':
	#pass in the username of the account you want to download
    alltweets=get_all_tweets("@midasIIITD")

1045784530282565631
1021377705084739583
1021377705084739583

In [67]:
consumer_key = "jQv1cDZDaSqYcqQzm2c8zCyEr" 
consumer_secret = "yyBkPNwLOGNoKMqrGAHxEQX0kHhBdRgrrDkWMb5oDk4rdqphcn"
access_key = "4732192388-paHKchCFcBPDlfcXfDFQuxDpvtCjfWrX3L30BYu"
access_secret = "0rTHWe6fldunlncROVSbIynbfYpMSVkDHHL2Fyul9TZ7E"
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_key, access_secret)
api = tweepy.API(auth)
user = api.get_user(id="@midasIIITD")
tweets=[]
for tweet in tweepy.Cursor(api.user_timeline, id=user.id, tweet_mode="extended").items():
    tweets.append(tweet._json)
    
#     num_images=0
   
#     for medium in tweet.entities.get("media",[{}]):
#         if medium.get("type",None) == "photo":
# #             print('hi')
#             num_images+=1
#     if num_images>0:
#         tweets.append([tweet.created_at,tweet.favorite_count,tweet.retweet_count,num_images])
#     else:
#         tweets.append([tweet.created_at,tweet.favorite_count,tweet.retweet_count,'None'])

In [68]:
print(len(tweets))
print(tweets[7])

304
{'created_at': 'Sun Mar 24 06:23:14 +0000 2019', 'id': 1109702192439582722, 'id_str': '1109702192439582722', 'full_text': 'RT @IEEEBigMM19: Distinguished researchers Dr. Rajiv Ratn Shah @RatnRajiv (@IIITDelhi , @midasIIITD ), Dr. Jianquan Liu (NEC Japan) and Dr.…', 'truncated': False, 'display_text_range': [0, 140], 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'IEEEBigMM19', 'name': 'IEEE BigMM 2019', 'id': 1108061173130223616, 'id_str': '1108061173130223616', 'indices': [3, 15]}, {'screen_name': 'RatnRajiv', 'name': 'Rajiv Ratn', 'id': 932847441316999169, 'id_str': '932847441316999169', 'indices': [63, 73]}, {'screen_name': 'IIITDelhi', 'name': 'IIIT Delhi', 'id': 2227868629, 'id_str': '2227868629', 'indices': [75, 85]}, {'screen_name': 'midasIIITD', 'name': 'MIDAS IIITD', 'id': 1021355762575073281, 'id_str': '1021355762575073281', 'indices': [88, 99]}], 'urls': []}, 'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>', 'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None, 'user': {'id': 1021355762575073281, 'id_str': '1021355762575073281', 'name': 'MIDAS IIITD', 'screen_name': 'midasIIITD', 'location': 'New Delhi, India', 'description': 'MIDAS is a group of researchers at IIIT-Delhi who study, analyze, and build different multimedia systems for society leveraging multimodal information.', 'url': 'https://t.co/Uwg7oSM6mE', 'entities': {'url': {'urls': [{'url': 'https://t.co/Uwg7oSM6mE', 'expanded_url': 'http://midas.iiitd.edu.in/', 'display_url': 'midas.iiitd.edu.in', 'indices': [0, 23]}]}, 'description': {'urls': []}}, 'protected': False, 'followers_count': 182, 'friends_count': 39, 'listed_count': 0, 'created_at': 'Mon Jul 23 11:26:04 +0000 2018', 'favourites_count': 125, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 304, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'F5F8FA', 'profile_background_image_url': None, 'profile_background_image_url_https': None, 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1021356444921212928/WmSTJCUs_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1021356444921212928/WmSTJCUs_normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1021355762575073281/1552394509', 'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None, 'retweeted_status': {'created_at': 'Sun Mar 24 05:58:27 +0000 2019', 'id': 1109695956159651840, 'id_str': '1109695956159651840', 'full_text': 'Distinguished researchers Dr. Rajiv Ratn Shah @RatnRajiv (@IIITDelhi , @midasIIITD ), Dr. Jianquan Liu (NEC Japan) and Dr. Vivek Singh (Rutgers University @RutgersU ) will be our technical program co-chairs.', 'truncated': False, 'display_text_range': [0, 207], 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'RatnRajiv', 'name': 'Rajiv Ratn', 'id': 932847441316999169, 'id_str': '932847441316999169', 'indices': [46, 56]}, {'screen_name': 'IIITDelhi', 'name': 'IIIT Delhi', 'id': 2227868629, 'id_str': '2227868629', 'indices': [58, 68]}, {'screen_name': 'midasIIITD', 'name': 'MIDAS IIITD', 'id': 1021355762575073281, 'id_str': '1021355762575073281', 'indices': [71, 82]}, {'screen_name': 'RutgersU', 'name': 'Rutgers University', 'id': 19272796, 'id_str': '19272796', 'indices': [155, 164]}], 'urls': []}, 'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>', 'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None, 'user': {'id': 1108061173130223616, 'id_str': '1108061173130223616', 'name': 'IEEE BigMM 2019', 'screen_name': 'IEEEBigMM19', 'location': 'Singapore', 'description': 'The Fifth IEEE International Conference on Multimedia Big Data | September 11-13, 2019 Singapore', 'url': 'https://t.co/2z8U2Pv3SF', 'entities': {'url': {'urls': [{'url': 'https://t.co/2z8U2Pv3SF', 'expanded_url': 'http://bigmm2019.org/', 'display_url': 'bigmm2019.org', 'indices': [0, 23]}]}, 'description': {'urls': []}}, 'protected': False, 'followers_count': 10, 'friends_count': 24, 'listed_count': 0, 'created_at': 'Tue Mar 19 17:42:25 +0000 2019', 'favourites_count': 13, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 12, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': '000000', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1108197071742558208/MjF3Pb2n_normal.png', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1108197071742558208/MjF3Pb2n_normal.png', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1108061173130223616/1553018846', 'profile_link_color': 'FAB81E', 'profile_sidebar_border_color': '000000', 'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000', 'profile_use_background_image': False, 'has_extended_profile': True, 'default_profile': False, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None, 'is_quote_status': False, 'retweet_count': 3, 'favorite_count': 13, 'favorited': False, 'retweeted': False, 'lang': 'en'}, 'is_quote_status': False, 'retweet_count': 3, 'favorite_count': 0, 'favorited': False, 'retweeted': False, 'lang': 'en'}

In [69]:
# import json
# with open('result.json', 'w') as fp:
#     json.dump(tweets, fp)

In [72]:
with open('result.json', 'r') as fp:
    tweets=json.load(fp)

In [102]:
table=[]
for tweet in tweets:
    num_images=0
    if tweet.get('entities'):         
        if tweet['entities'].get('media'):
            for medium in tweet['entities']['media']:
                if medium.get('type') == "photo":
                    num_images+=1
    if num_images>0:
        dic=[tweet['created_at'],tweet['favorite_count'],tweet['retweet_count'],num_images]
    else:
        dic=[tweet['created_at'],tweet['favorite_count'],tweet['retweet_count'],'None']
    table.append(dic)

In [104]:
import pandas as pd
pd.DataFrame(table,columns=['created_at','favorite_count','retweet_count','num_images'])

                         created_at  favorite_count  retweet_count num_images
0    Tue Mar 26 05:54:49 +0000 2019               1              0       None
1    Tue Mar 26 05:50:10 +0000 2019               0              3       None
2    Mon Mar 25 13:01:57 +0000 2019              15              1          1
3    Sun Mar 24 18:44:01 +0000 2019               8              3       None
4    Sun Mar 24 18:26:02 +0000 2019               0              4       None
5    Sun Mar 24 11:34:27 +0000 2019               4              0       None
6    Sun Mar 24 06:23:37 +0000 2019               0              5       None
7    Sun Mar 24 06:23:14 +0000 2019               0              3       None
8    Wed Mar 20 08:19:24 +0000 2019               1              1       None
9    Wed Mar 20 02:40:07 +0000 2019               0              5       None
10   Mon Mar 18 02:27:47 +0000 2019               6              3       None
11   Sun Mar 17 14:22:04 +0000 2019              15              4       None
12   Sat Mar 16 14:06:56 +0000 2019               7              0       None
13   Sat Mar 16 09:20:29 +0000 2019               1              1       None
14   Sat Mar 16 09:14:58 +0000 2019               7              2       None
15   Sat Mar 16 05:13:14 +0000 2019               7              2       None
16   Wed Mar 13 17:09:44 +0000 2019               0              2       None
17   Wed Mar 13 04:11:24 +0000 2019               1              0          1
18   Wed Mar 13 04:06:04 +0000 2019               0             13       None
19   Tue Mar 12 17:43:44 +0000 2019               0             69       None
20   Tue Mar 12 14:37:55 +0000 2019              16              4          1
21   Mon Mar 11 14:58:30 +0000 2019               0              0       None
22   Mon Mar 11 12:02:42 +0000 2019               4              0       None
23   Mon Mar 11 11:54:38 +0000 2019               3              0       None
24   Mon Mar 11 06:22:12 +0000 2019               1              1       None
25   Mon Mar 11 06:17:20 +0000 2019               0             64       None
26   Fri Mar 08 13:22:07 +0000 2019               1              0       None
27   Fri Mar 08 13:15:34 +0000 2019               8              4       None
28   Wed Mar 06 13:44:11 +0000 2019               3              0       None
29   Wed Mar 06 11:12:30 +0000 2019               0             22          1
..                              ...             ...            ...        ...
274  Thu Aug 09 05:59:57 +0000 2018               0            265       None
275  Wed Aug 08 11:30:56 +0000 2018               2              1       None
276  Wed Aug 08 05:53:48 +0000 2018               3              1          1
277  Wed Aug 08 05:45:58 +0000 2018               0              1       None
278  Tue Aug 07 07:16:33 +0000 2018               0             40          1
279  Tue Aug 07 02:05:12 +0000 2018               1              1       None
280  Tue Aug 07 01:58:49 +0000 2018               1              1       None
281  Tue Aug 07 01:50:33 +0000 2018               1              1       None
282  Mon Aug 06 17:48:23 +0000 2018               0              0       None
283  Mon Aug 06 17:46:59 +0000 2018               0            103          1
284  Mon Aug 06 06:06:47 +0000 2018               0              0       None
285  Fri Aug 03 05:56:33 +0000 2018               6              1       None
286  Wed Aug 01 11:47:15 +0000 2018               5              1          1
287  Wed Aug 01 11:20:07 +0000 2018               0              4       None
288  Wed Aug 01 05:06:47 +0000 2018               0              4       None
289  Tue Jul 31 12:11:52 +0000 2018               1              0       None
290  Tue Jul 31 02:06:26 +0000 2018               0            263       None
291  Mon Jul 30 07:30:51 +0000 2018               0              2       None
292  Sat Jul 28 11:07:11 +0000 2018               0             57       None
293  Sat Jul 28 06:14:09 +0000 2018               0            105       None
294  Sat Jul 28 06:13:48 +0000 2018               0              7       None
295  Sat Jul 28 04:08:21 +0000 2018               0              6       None
296  Fri Jul 27 06:46:44 +0000 2018               3              2       None
297  Fri Jul 27 04:07:31 +0000 2018               8              2       None
298  Wed Jul 25 05:14:35 +0000 2018               5              1       None
299  Tue Jul 24 10:33:23 +0000 2018               2              1       None
300  Tue Jul 24 10:12:34 +0000 2018               2              1       None
301  Tue Jul 24 09:46:26 +0000 2018               4              1          1
302  Mon Jul 23 16:25:05 +0000 2018               3              1       None
303  Mon Jul 23 12:53:15 +0000 2018               7              4       None

[304 rows x 4 columns]

In [27]:
# The text of the tweet.
# ● Date and time of the tweet.
# ● The number of favorites/likes.
# ● The number of retweets.
# ● Number of Images present in Tweet. If no image returns None